modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="charken"
version="1.5.1"
displayName="Charken"
displayURL="https://modrinth.com/mod/charken"
logoFile="logo.png"
credits="Created with MCreator. All Ideas and models by JacobA0225 and Bumstronaut"
authors="JacobA0225, Bumstronaut"
description="The Charken Mod"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.charken]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.charken]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration